# Generated by Django 3.2.7 on 2021-11-28 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_item_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='List Date')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.list')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
